### ISSUE TITLE
uninitialized constant Zip::Error (NameError)

### ISSUE THREAD

**Issue by djvdorp** [cobalamin/drip-downloader#2]
Heya,

it's me again. I still like the tool a lot, but recently I started getting this error:
```ruby
We've got "Hospitality 2012" by Various Artists.
Saving to "Hospital Records/various-artists-hospitality-2012.zip"...
Please stand by while this release is being fetched...
Unpacking Hospitality 2012...
drip.rb:317:in `rescue in unpack_release': uninitialized constant Zip::Error (NameError)
        from drip.rb:310:in `unpack_release'
        from drip.rb:278:in `fetch_release'
        from drip.rb:231:in `block in grab_releases'
        from drip.rb:204:in `each'
        from drip.rb:204:in `grab_releases'
        from drip.rb:137:in `initialize'
        from drip.rb:350:in `new'
        from drip.rb:350:in `<main>'
```

Any clue what broke?

**Comment by cobalamin** [comment]
What's the output of `bundle` inside the downloader directory?

**Comment by djvdorp** [comment]
@cobalamin I am very sorry for the slow reply (got no mail notification or something) and for bothering you, after re-installing all gems needed all is well again, so it was a hickup in my setup, sorry!

**Comment by cobalamin** [comment]
Don't worry about it, didn't bother me at all :)
