### ISSUE TITLE
We're sorry, but something went wrong

### ISSUE THREAD

**Issue by bendwyer** [cobalamin/drip-downloader#8]
I'm getting a new error when trying to download from Drip. I think something may have changed on their end. I've included what I could gather of the error message below, but I'm not sure how helpful it will be.

```
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
  }

  div.dialog {
    width: 25em;
    margin: 4em auto 0 auto;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 4em 0 4em;
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  body > p {
    width: 33em;
    margin: 0 auto 1em;
    padding: 1em 0;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow:0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <h1>We're sorry, but something went wrong.</h1>
  </div>
  <p>If you are the application owner check the logs for more information.</p>
</body>
</html>
'
        from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
        from /home/ben/drip/drip.rb:193:in `set_releases'
        from /home/ben/drip/drip.rb:139:in `initialize'
        from /home/ben/drip/drip.rb:354:in `new'
        from /home/ben/drip/drip.rb:354:in `<main>'
```

**Comment by cobalamin** [comment]
Yeah they definitely did, thanks for letting me know. Gonna have to rewrite some chunk of this code to use the Library functionality instead.

**Comment by bendwyer** [comment]
@cobalamin - it looks like the Drip site as we know it is closing on Dec. 15. Do you think you'll have a chance to update to code before then? If not, no worries.

**Comment by cobalamin** [comment]
Finally got around to it, sorry it's so late. It's now just a stripped down version that gets each and every one of your releases, so you can save everything.
